spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: info