spring:
  profiles:
    active:
      - prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: local
    import: secret/application-local-config.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: secret/application-prod-config.yml


